### ISSUE TITLE
Re-implement green Filter / double dropdown

### ISSUE THREAD

**Issue by eldain** [julietnpn/sage#19]
Not sure exactly what this will look like, might be worth looking at other heavy filtering examples (like job boards Glassdoor/Indeed)

Might be time to introduce front-end framework to project to help fix this. If we go w/ React, could use https://github.com/paypal/downshift to help speed up dropdown / filtering abilities

**Comment by julietnpn** [comment]
so i like the accessibility features of downshift, but since (i think) it relies on client side computing, is that ok considering the wide range of OS requirements our users have (e.g. dreadfully out dated to recent)? I'm not really sure what is best in this situation.

**Comment by eldain** [comment]
Do we have a list of browsers that we're aiming to support?

If we were to add in a JS framework like React, I think we would still be covering a wide (enough?) range of browsers: https://reactjs.org/docs/react-dom.html#browser-support

While adding in a tool like React can be a pretty big jump in the required dev setup, it would also give us a chance to add some other nice developer tools to easily do vendor prefixing and clean up the code a bit.
