### ISSUE TITLE
Add description and website to top of GitHub page

### ISSUE THREAD

**Issue by eldain** [julietnpn/sage#4]
This is mostly an aesthetic change, but it does add a nice touch if people add this project to their pinned repositories. I think only maintainers of a project can do this. Here's an example of what it would look like as a pinned repository or when popping up in a search:
<img width="368" alt="screen shot 2018-07-08 at 19 42 00" src="https://user-images.githubusercontent.com/9837491/42428149-1cd980da-82e7-11e8-8f14-b2734431d7e3.png">

I'll suggest 🌿this emoji, as it seems to be the closest to actually looking like sage

**Comment by julietnpn** [comment]
Whatcha think?

**Comment by eldain** [comment]
Looks great, thanks @julietnpn 🙂
